name: AMusic
main: me.bomb.amusic.bukkit.AMusicBukkit
version: ${revision}
api-version: 1.13
author: Bomb
folia-supported: true
commands:
  uploadmusic:
  loadmusic:
  playmusic:
  playmusicuntrackable:
  repeat:
