host: 127.0.0.1
port: 25530
processpack: true
checkpackstatus: true
packapplystatus: true #1.13.2-
cache:
  server: true
  client: true
strictdownloaderlist: true
#encoder:
#  bitrate: 64000
#  channels: 2
#  samplingrate: 44100
#  async: true