name: AMusic
main: me.bomb.amusic.glowstone.AMusicGlowstone
version: ${revision}
api-version: 1.13
author: Bomb
softdepend: ["Geyser-Spigot"]
commands:
  uploadmusic:
  loadmusic:
  playmusic:
  playmusicuntrackable:
  repeat:
