host: 127.0.0.1
port: 25530
processpack: true
checkpackstatus: true
packapplystatus: false
cache: true
strictdownloaderlist: true
#encoder:
#  ffmpegbinarypath: plugins/AMusic/ffmpeg
#  bitrate: 64000
#  channels: 2
#  samplingrate: 44100
#  async: true